export { Hero } from './Hero'
export { About } from './About'
export { Projects } from './Projects'
export { Skills } from './Skills'
export { ParallaxShowcase } from './ParallaxShowcase'
export { Contact } from './Contact'
